# Netlify配置 for Next.js
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # 数据库环境变量
  DB_HOST = "121.41.65.220"
  DB_PORT = "3306"
  DB_USER = "h5_cloud_user"
  DB_PASSWORD = "mc72TNcMmy6HCybH"
  DB_NAME = "h5_cloud_db"
  JWT_SECRET = "sn8we6nRudHjsDnso7h3Qzpr5Pax8Jwe"
  NETLIFY = "true"
