# Netlify配置 - 自动生成
[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # 为Netlify Functions设置环境变量
  DB_HOST = "8.149.244.105"
  DB_PORT = "3306"
  DB_USER = "h5_cloud_user"
  DB_PASSWORD = "mc72TNcMmy6HCybH"
  DB_NAME = "h5_cloud_db"
  JWT_SECRET = "sn8we6nRudHjsDnso7h3Qzpr5Pax8Jwe"

# Netlify Functions配置
[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"

# API函数特殊配置
[[functions]]
  path = "/api/*"
  included_files = ["lib/**", "components/**"]

# 静态资源处理规则
[[redirects]]
  from = "/logo.svg"
  to = "/logo.svg"
  status = 200
  force = true

[[redirects]]
  from = "/*.svg"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# API路由重定向
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# 缓存配置
[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API函数的CORS配置
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
