# Netlify配置
[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # 为Netlify Functions设置环境变量 - 使用代理端口
  DB_HOST = "8.149.244.105"
  DB_PORT = "3308"  # 使用代理端口而不是直接连接MySQL
  DB_USER = "h5_cloud_user"
  DB_PASSWORD = "mc72TNcMmy6HCybH"
  DB_NAME = "h5_cloud_db"
  JWT_SECRET = "sn8we6nRudHjsDnso7h3Qzpr5Pax8Jwe"
  # 启用数据库连接调试
  DB_DEBUG = "true"

# 静态资源处理规则
[[redirects]]
  from = "/logo.svg"
  to = "/logo.svg"
  status = 200
  force = true

[[redirects]]
  from = "/*.svg"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# 缓存配置
[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API函数的CORS配置
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
